<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.bahmni.module</groupId>
        <artifactId>elis-fhir-result-support</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>elis-fhir-result-support-omod</artifactId>
    <packaging>jar</packaging>
    <name>ELIS FHIR Result Support OMOD</name>
    <description>OpenMRS module packaging for ELIS FHIR Result Support</description>

    <dependencies>
        <dependency>
            <groupId>org.bahmni.module</groupId>
            <artifactId>elis-fhir-result-support-api</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openmrs.api</groupId>
            <artifactId>openmrs-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openmrs.module</groupId>
            <artifactId>fhir2-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.bahmni.module</groupId>
            <artifactId>fhir2addlextension-api</artifactId>
        </dependency>
    </dependencies>

    <pluginRepositories>
        <pluginRepository>
            <id>openmrs-repo</id>
            <name>OpenMRS Nexus Repository</name>
            <url>https://mavenrepo.openmrs.org/public</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <finalName>${project.parent.artifactId}-${project.parent.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.openmrs.maven.plugins</groupId>
                <artifactId>maven-openmrs-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
