name: Maven Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven
          server-id: nexus-sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build and deploy with Maven
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "Building and deploying snapshot version: $VERSION"
            ./mvnw --no-transfer-progress clean -U deploy
          else
            echo "Skipping deployment for release version: $VERSION"
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
